apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-eureka-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecom-eureka-server
  template:
    metadata:
      labels:
        app: ecom-eureka-server
    spec:
      containers:
      - name: ecom-eureka-server
        image: your-dockerhub-username/ecom-eureka-server:latest
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
  - protocol: TCP
    port: 8761
    targetPort: 8761
