Server :
  Port : 10003
Spring :
  datasource :
    mongodb :
      uri : mongodb://localhost:27107/user
  application:
    name: api-gateway
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

