server:
  port: 10003
spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27107/user}
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET:Zm9yX3NlY3VyZS1qd3Qtc2VydmljZS1wcm9qZWN0LWtleQ==}
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
jwt:
  secret: ${JWT_SECRET:Zm9yX3NlY3VyZS1qd3Qtc2VydmljZS1wcm9qZWN0LWtleQ==}
  access-token-expiration-ms: 900000
  refresh-token-expiration-ms: 604800000

